import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="min-h-screen p-2 flex flex-col justify-center items-center h-screen">
      <Head>
        <title>グルgram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <h1 className="text-3xl font-bold underline">
        Hello world!
      </h1>
      </main>

    </div>
  )
}
