import { useRouter } from "next/router";
import { getPostList } from "../lib/posts";
import Layout from "../components/Layout";
import Head from "next/head";
import Post from "../components/Post";

export default function MainPage({ filteredPosts }) {
  const router = useRouter();

  return (
    <Layout title="Main">
      <Head>
        <title>グルgram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          {Array.isArray(filteredPosts) &&
            filteredPosts.map((post) => <Post key={post.id} post={post} />)}
        </ul>
        <h1 className="text-2xl font-bold mb-4">Coming Soon...</h1>
      </main>
    </Layout>
  );
}

export async function getStaticProps() {
  const filteredPosts = await getPostList();
  console.log(filteredPosts);
  return {
    props: { filteredPosts },
  };
}
