import Cookie from "universal-cookie";
import { useReducer } from "react";
import { useRouter } from "next/router";
import Layout from "../components/Layout";
import Head from "next/head";

const cookie = new Cookie();

export default function MainPage() {
  const router = useRouter();
  const logout = () => {
    cookie.remove("access_token");
    router.push("/");
  };
  return (
    <Layout title="Main">
      <Head>
        <title>グルgram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-2xl font-bold mb-4">Coming Soon...</h1>
      </main>
    </Layout>
  );
}
