import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Cookie from "universal-cookie";
import Layout from "../components/Layout";
import Head from "next/head";
import Post from "../components/Post";

const cookie = new Cookie();

export default function MainPage() {
  const router = useRouter();
  const [filteredPosts, setFilteredPosts] = useState([]);

  useEffect(() => {
    const fetchPosts = async () => {
      const token = cookie.get("access_token");
      console.log(token);
      const res = await fetch(
        `${process.env.NEXT_PUBLIC_RESTAPI_URL}api/post/`,
        {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
            Authorization: `JWT ${token}`,
          },
        }
      );
      const posts = await res.json();
      setFilteredPosts(posts);
    };
    fetchPosts();
  }, []);

  return (
    <Layout title="Main">
      <Head>
        <title>グルgram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          {Array.isArray(filteredPosts) &&
            filteredPosts.map((post) => <Post key={post.id} post={post} />)}
        </ul>
        <h1 className="text-2xl font-bold mb-4">Coming Soon...</h1>
      </main>
    </Layout>
  );
}
