import Layout from "../components/Layout";
import Head from "next/head";

export default function Review() {
  return (
    <Layout title="Review">
      <Head>
        <title>グルgram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-2xl font-bold mb-4">Coming Soon...</h1>
      </main>
    </Layout>
  );
}
