import Layout from "../components/Layout"
import Head from "next/head"

export default function Search(){
    return (
        <Layout title="Search">
            <Head>
                <title>グルgram</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </Layout>
    )
}